backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "static/images"
public_folder: "/images"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Menus"
        name: "menus"
        file: "content/menus.yml"
        fields: 
          - {label: Date, name: date, widget: string}
          - label: "Menu"
            name: "menu"
            widget: "image"
            choose_url: true
            default: "/static/images/menu_1.png"
            media_library:
                config:
                  multiple: true     
      - label: "Prix"
        name: "prix"
        file: "content/prix.yml"
        fields: 
          - {label: Fringale, name: fringale, widget: number}
          - {label: Supplément Flexi Fringale, name: fringaleFlexi, widget: number}
          - {label: Curcufamille, name: curcufamille, widget: number}
          - {label: Supplément Flexi Curcufamille, name: curcufamilleFlexi, widget: number}
          - {label: Carte cadeau 10 jours, name: cc10j, widget: number}
          - {label: Supplément Flexi Carte cadeau 10 jours, name: cc10jFlexi, widget: number}
          - {label: Carte cadeau 14 jours, name: cc14j, widget: number}
          - {label: Supplément Flexi Carte cadeau 14 jours, name: cc14jFlexi, widget: number}
          - {label: Carte cadeau 30 jours, name: cc30j, widget: number}
          - {label: Supplément Flexi Carte cadeau 30 jours, name: cc30jFlexi, widget: number}