backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Menus"
        name: "menus"
        file: "content/menus.yml"
        fields: 
          - {label: Date 1, name: date_1, widget: string}
          - label: "Menu 1"
            name: "menu_1"
            widget: "image"
            choose_url: true
            default: "/static/images/menu_1.png"
            media_library:
                config:
                  multiple: true   
          - {label: Date 2, name: date_2, widget: string}
          - label: "Menu 1"
            name: "menu_2"
            widget: "image"
            choose_url: true
            default: "/static/images/menu_2.png"
            media_library:
                config:
                  multiple: true   