backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "static/images"
public_folder: "/images"

collections:
  - label: "Dates"
    name: "dates"
    files:
      - label: "Dates"
        name: "dates"
        file: "content/dates.yml"
        fields: 
          - {label: Date1, name: date1, widget: string}
          - {label: Date2, name: date2, widget: string}
          - {label: Date3, name: date3, widget: string}
          - {label: Date4, name: date4, widget: string}
  - label: "Menus"
    name: "menus"
    files:
      - label: "Entrées"
        name: "entrees"
        file: "content/entrees.yml"
        fields: 
          - {label: "Nom 1", name: nom1, widget: string}
          - {label: "Informations nutritionnelles 1", name: infoNut1, widget: string}
          - {label: "Description 1", name: description1, widget: string}  
          - label: "Image 1"
            name: "image1"
            widget: "image"
            choose_url: true
            default: "/static/images/menu_1.png"
            media_library:
                config:
                  multiple: true
          - {label: "Nom 2", name: nom2, widget: string}
          - {label: "Informations nutritionnelles 2", name: infoNut2, widget: string}
          - {label: "Description 2", name: description2, widget: string}  
          - label: "Image 2"
            name: "image2"
            widget: "image"
            choose_url: true
            default: "/static/images/menu_1.png"
            media_library:
                config:
                  multiple: true
          - {label: "Nom 3", name: nom3, widget: string}
          - {label: "Informations nutritionnelles 3", name: infoNut3, widget: string}
          - {label: "Description 3", name: description3, widget: string}  
          - label: "Image 3"
            name: "image3"
            widget: "image"
            choose_url: true
            default: "/static/images/menu_1.png"
            media_library:
                config:
                  multiple: true
          - {label: "Nom 4", name: nom4, widget: string}
          - {label: "Informations nutritionnelles 4", name: infoNut4, widget: string}
          - {label: "Description 4", name: description4, widget: string}  
          - label: "Image 4"
            name: "image4"
            widget: "image"
            choose_url: true
            default: "/static/images/menu_1.png"
            media_library:
                config:
                  multiple: true
      - label: "Plats"
        name: "plats"
        file: "content/plats.yml"
        fields: 
          - {label: "Nom 1", name: nom1, widget: string}
          - {label: "Informations nutritionnelles 1", name: infoNut1, widget: string}
          - {label: "Description 1", name: description1, widget: string}  
          - label: "Image 1"
            name: "image1"
            widget: "image"
            choose_url: true
            default: "/static/images/menu_1.png"
            media_library:
                config:
                  multiple: true
          - {label: "Nom 2", name: nom2, widget: string}
          - {label: "Informations nutritionnelles 2", name: infoNut2, widget: string}
          - {label: "Description 2", name: description2, widget: string}  
          - label: "Image 2"
            name: "image2"
            widget: "image"
            choose_url: true
            default: "/static/images/menu_1.png"
            media_library:
                config:
                  multiple: true
          - {label: "Nom 3", name: nom3, widget: string}
          - {label: "Informations nutritionnelles 3", name: infoNut3, widget: string}
          - {label: "Description 3", name: description3, widget: string}  
          - label: "Image 3"
            name: "image3"
            widget: "image"
            choose_url: true
            default: "/static/images/menu_1.png"
            media_library:
                config:
                  multiple: true
          - {label: "Nom 4", name: nom4, widget: string}
          - {label: "Informations nutritionnelles 4", name: infoNut4, widget: string}
          - {label: "Description 4", name: description4, widget: string}  
          - label: "Image 4"
            name: "image4"
            widget: "image"
            choose_url: true
            default: "/static/images/menu_1.png"
            media_library:
                config:
                  multiple: true
      - label: "Desserts"
        name: "desserts"
        file: "content/desserts.yml"
        fields: 
          - {label: "Nom 1", name: nom1, widget: string}
          - {label: "Informations nutritionnelles 1", name: infoNut1, widget: string}
          - {label: "Description 1", name: description1, widget: string}  
          - label: "Image 1"
            name: "image1"
            widget: "image"
            choose_url: true
            default: "/static/images/menu_1.png"
            media_library:
                config:
                  multiple: true
          - {label: "Nom 2", name: nom2, widget: string}
          - {label: "Informations nutritionnelles 2", name: infoNut2, widget: string}
          - {label: "Description 2", name: description2, widget: string}  
          - label: "Image 2"
            name: "image2"
            widget: "image"
            choose_url: true
            default: "/static/images/menu_1.png"
            media_library:
                config:
                  multiple: true
          - {label: "Nom 3", name: nom3, widget: string}
          - {label: "Informations nutritionnelles 3", name: infoNut3, widget: string}
          - {label: "Description 3", name: description3, widget: string}  
          - label: "Image 3"
            name: "image3"
            widget: "image"
            choose_url: true
            default: "/static/images/menu_1.png"
            media_library:
                config:
                  multiple: true
          - {label: "Nom 4", name: nom4, widget: string}
          - {label: "Informations nutritionnelles 4", name: infoNut4, widget: string}
          - {label: "Description 4", name: description4, widget: string}  
          - label: "Image 4"
            name: "image4"
            widget: "image"
            choose_url: true
            default: "/static/images/menu_1.png"
            media_library:
                config:
                  multiple: true

  - label: "Formules"
    name: "formules"
    files:
      - label: "Fringale"
        name: "fringale"
        file: "content/fringale.yml"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Description,
            name: description,
            widget: string
          }
          - {label: Lien de paiement, name: lienPaiement, widget: string}
          - {label: Cadeau, name: isCadeau, widget: boolean}
          - {label: "Nombre de repas", name: nbRepas, widget: number}
          - {label: "Prix végé", name: priceVG, widget: number}
          - {label: "Prix flexi", name: priceFlexi, widget: number}
          - label: "Image"
            name: "image"
            widget: "image"
            choose_url: true
            default: "/static/images/menu_1.png"
            media_library:
                config:
                  multiple: true
      - label: "Curcufamille"
        name: "curcufamille"
        file: "content/curcufamille.yml"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Description,
            name: description,
            widget: string
          }
          - {label: Lien de paiement, name: lienPaiement, widget: string}
          - {label: Cadeau, name: isCadeau, widget: boolean}
          - {label: "Nombre de repas", name: nbRepas, widget: number}
          - {label: "Prix végé", name: priceVG, widget: number}
          - {label: "Prix flexi", name: priceFlexi, widget: number}
          - label: "Image"
            name: "image"
            widget: "image"
            choose_url: true
            default: "/static/images/menu_1.png"
            media_library:
                config:
                  multiple: true      
      - label: "Curcutribu"
        name: "curcutribu"
        file: "content/curcutribu.yml"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Description,
            name: description,
            widget: string
          }
          - {label: Lien de paiement, name: lienPaiement, widget: string}
          - {label: Cadeau, name: isCadeau, widget: boolean}
          - {label: "Nombre de repas", name: nbRepas, widget: number}
          - {label: "Prix végé", name: priceVG, widget: number}
          - {label: "Prix flexi", name: priceFlexi, widget: number}
          - label: "Image"
            name: "image"
            widget: "image"
            choose_url: true
            default: "/static/images/menu_1.png"
            media_library:
                config:
                  multiple: true     
      - label: "Curcuvillage"
        name: "curcuvillage"
        file: "content/curcuvillage.yml"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Description,
            name: description,
            widget: string
          }
          - {label: Lien de paiement, name: lienPaiement, widget: string}
          - {label: Cadeau, name: isCadeau, widget: boolean}
          - {label: "Nombre de repas", name: nbRepas, widget: number}
          - {label: "Prix végé", name: priceVG, widget: number}
          - {label: "Prix flexi", name: priceFlexi, widget: number}
          - label: "Image"
            name: "image"
            widget: "image"
            choose_url: true
            default: "/static/images/menu_1.png"
            media_library:
                config:
                  multiple: true     
      - label: "Curcu mois d'or"
        name: "curcumoisdor"
        file: "content/curcumoisdor.yml"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Description,
            name: description,
            widget: string
          }
          - {label: Lien de paiement, name: lienPaiement, widget: string}
          - {label: Cadeau, name: isCadeau, widget: boolean}
          - {label: "Nombre de repas", name: nbRepas, widget: number}
          - {label: "Prix végé", name: priceVG, widget: number}
          - {label: "Prix flexi", name: priceFlexi, widget: number}
          - label: "Image"
            name: "image"
            widget: "image"
            choose_url: true
            default: "/static/images/menu_1.png"
            media_library:
                config:
                  multiple: true     
                